services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - leban-network

  leban-app:
    build: .
    restart: unless-stopped
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      # Base de datos
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

      # Aplicaci√≥n
      SPRING_APPLICATION_NAME: ${APP_NAME}
      SERVER_PORT: ${SERVER_PORT}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}

      # JPA/Hibernate
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${JPA_HIBERNATE_DDL_AUTO}
      SPRING_JPA_SHOW_SQL: ${JPA_SHOW_SQL}
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: ${JPA_FORMAT_SQL}
    depends_on:
      - postgres
    networks:
      - leban-network

volumes:
  postgres_data: {}

networks:
  leban-network:
    driver: bridge

